behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1000000
      learning_rate: 0.0001
      beta: 0.02
      epsilon: 0.2
      lambd: 0.999
      num_epoch: 4
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 200000
    time_horizon: 1000
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
